name: Anchore LLVM Repo scan

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    name: docker image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Clone repo
        run: git clone https://github.com/llvm/llvm-project
        
      - name: Scan image
        uses: anchore/scan-action@v3
        
        with:
          path: "./llvm-project"
          severity-cutoff: critical
          fail-build: false
          output-format: table
