name: Anchore Red Hat Docker Scan

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Login
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin docker.io

    - name: Pull Red Hat Docker Image
      run: docker pull docker.io/redhat/ubi8
        
    - name: Scan image
      uses: anchore/scan-action@v3
      
      with:
        image: redhat/ubi8
        severity-cutoff: critical
        fail-build: false
        output-format: sarif
        
    - name: Anchore SBOM Action
      # You may pin to the exact commit or the version.
      # uses: anchore/sbom-action@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1
      uses: anchore/sbom-action@v0.14.3
      with:
        image: redhat/ubi8
        format: spdx-json
        output-file: sbom.txt
    - name: Save Anchore Scan Results
      run: |
        # Create a results folder if it doesn't exist
        mkdir -p results

        # Generate a filename with the Docker image name and a timestamp
        filename="redhat_ubi8_anchore_vuln_$(date +'%Y%m%d%H%M%S').txt"
        sbomname="redhat_ubi8_sbom_$(date +'%Y%m%d%H%M%S').txt"

        # Save the Anchore scan results to the generated filename
        mv results.sarif results/$filename
        mv sbom.txt results/$sbomname

        # Commit the results to the Git repository
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add results/$filename
        git add results/$sbomname
        git commit -m "Add Anchore scan results for redhat/ubi8"
        git push

        echo "Results saved as $filename"

      env:
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: actions@github.com
      working-directory: ${{ github.workspace }}
