name: Trivy Red Hat Docker Image scan

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan:
    name: docker image Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull Red Hat Docker Image
        run: docker pull docker.io/redhat/ubi8

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/redhat/ubi8'
          format: 'table'
          exit-code: '1'
          scanners: vuln,secret,config
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: result.txt
      - name: List files after scan
        run: |
          ls -la
          cat result.txt
        
