name: Pull Red Hat Docker Image and Download RPM

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Login
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin docker.io

    - name: Pull Red Hat Docker Image
      run: docker pull docker.io/redhat/ubi8

    - name: Run a Docker container in detached mode
      run: docker run -d --name my-ubi8-container docker.io/redhat/ubi8 sleep infinity
    
    - name: Install yum (inside the container)
      run: docker exec my-ubi8-container dnf install -y wget
      
    - name: Download RPM package
      run: docker exec my-ubi8-container wget -O /tmp/package.rpm "https://download1.rpmfusion.org/free/el/updates/8/x86_64/m/mplayer-1.5-1.el8.x86_64.rpm"
    
    - name: Install RPM package inside the Docker container
      run: docker exec my-ubi8-container rpm -ivh /tmp/package.rpm

    - name: Scan the Docker container with Anchore
      run: |
        docker exec my-ubi8-container anchore-cli image add my-ubi8-container
        docker exec my-ubi8-container anchore-cli image wait my-ubi8-container
        docker exec my-ubi8-container anchore-cli image content my-ubi8-container
        docker exec my-ubi8-container anchore-cli evaluate check my-ubi8-container
        docker exec my-ubi8-container anchore-cli report list my-ubi8-container

    - name: Stop and remove the Docker container
      run: docker stop my-ubi8-container && docker rm my-ubi8-container
