name: Pull Red Hat Docker Image and Download RPM

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Login
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin quay.io

    - name: Pull Red Hat Docker Image
      run: docker pull quay.io/redhat/ubi8

    - name: Run a Docker container
      run: docker run -it quay.io/redhat/ubi8 /bin/bash

    - name: Install wget (inside the container)
      run: yum install -y wget

    - name: Download RPM package
      run: wget -O /path/to/save/package.rpm "https://example.com/path/to/package.rpm"

    - name: Exit the Docker container
      run: exit
